# Generated by Django 4.0.1 on 2022-08-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('edition', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BeverageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('edition', models.CharField(max_length=200)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Untersetzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=5)),
                ('glass_level', models.IntegerField(default=0)),
                ('timeout', models.BooleanField()),
                ('description', models.CharField(max_length=200)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='untersetzerBroker.table')),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='coasters',
            field=models.ManyToManyField(related_name='coasterForTable', to='untersetzerBroker.Untersetzer'),
        ),
        migrations.CreateModel(
            name='lastBeverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_beverage', to='untersetzerBroker.beverage')),
            ],
        ),
        migrations.AddField(
            model_name='beverage',
            name='coaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beverage', to='untersetzerBroker.untersetzer'),
        ),
    ]
