# Generated by Django 4.0.1 on 2022-01-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untersetzerBroker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='untersetzer',
            name='identifier',
            field=models.CharField(default='0001', max_length=5),
            preserve_default=False,
        ),
    ]
