# Generated by Django 4.0.1 on 2022-08-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untersetzerBroker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempCoasterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('coasters', models.ManyToManyField(to='untersetzerBroker.Untersetzer')),
            ],
        ),
    ]
