# Generated by Django 4.2.5 on 2024-07-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('untersetzerBroker', '0002_remove_checkout_coaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutpositions',
            name='checkout',
        ),
    ]
