# Generated by Django 4.0.1 on 2022-08-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('untersetzerBroker', '0002_tempcoastergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceCall', to='untersetzerBroker.untersetzer')),
            ],
        ),
        migrations.CreateModel(
            name='QuickAccessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='untersetzerBroker.beveragetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='paymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('coaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='untersetzerBroker.untersetzer')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('coaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='untersetzerBroker.untersetzer')),
            ],
        ),
    ]
