# Generated by Django 4.0.1 on 2022-02-17 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('untersetzerBroker', '0003_table_beverage_alter_untersetzer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='lastBeverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_beverage', to='untersetzerBroker.beverage')),
            ],
        ),
    ]
