# Generated by Django 4.0.1 on 2022-09-11 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('untersetzerBroker', '0003_servicecall_quickaccesstemplate_paymentrequest_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAccessTemplateFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='untersetzerBroker.foodtemplate')),
            ],
        ),
    ]
