# Generated by Django 4.0.1 on 2022-09-12 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('untersetzerBroker', '0005_remove_tempcoastergroup_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcoastergroup',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_for_tempgroup', to='untersetzerBroker.table'),
        ),
    ]
