# Generated by Django 4.2.4 on 2023-09-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('untersetzerBroker', '0006_tempcoastergroup_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentSuccess', to='untersetzerBroker.untersetzer')),
            ],
        ),
    ]
